/**
 * @tryit/engine/providers/google-vto — Google Virtual Try-On adapter (config-gated).
 *
 * Maps a {@link TryOnRequest} into a Google VTO `:predict` instance, runs it through an
 * INJECTED HTTP client, and maps the prediction back into a validated {@link TryOnResult}.
 * The client is injected so unit tests supply a fixture and no network is touched. Google's
 * VTO returns generated bytes as base64, so this adapter expects the injected client to surface
 * a hosted https URL (the storage step lives outside this adapter); fail-closed if absent.
 * Only wired in when the tenant allow-lists `google-vto`.
 */

import type { TryOnRequest, TryOnResult } from '@tryit/contracts';
import type { ProviderContext, TryOnProvider } from '../provider.js';
import { imageRefToInput } from '../internal/image_ref_to_input.js';
import { validateProviderResult } from '../internal/validate_provider_result.js';

/** A single VTO prediction, narrowed to the field this adapter consumes. */
export interface GoogleVtoPrediction {
  readonly resultImageUrl?: unknown;
}

/** The Google VTO `:predict` response envelope. */
export interface GoogleVtoResponse {
  readonly predictions?: ReadonlyArray<GoogleVtoPrediction> | undefined;
}

/** The injected HTTP client wrapping the VTO `:predict` endpoint. */
export interface GoogleVtoHttpClient {
  predict(
    request: {
      instances: ReadonlyArray<Record<string, unknown>>;
      parameters: Record<string, unknown>;
    },
    signal: AbortSignal,
  ): Promise<GoogleVtoResponse>;
}

/** Options for the Google VTO adapter. */
export interface GoogleVtoProviderOptions {
  /** Injected HTTP client. Required so no network client is constructed implicitly. */
  readonly httpClient: GoogleVtoHttpClient;
  /** Cost attributed per successful call. */
  readonly costPerCallUsd?: number | undefined;
}

export class GoogleVtoProvider implements TryOnProvider {
  public readonly id = 'google-vto' as const;
  private readonly httpClient: GoogleVtoHttpClient;
  private readonly costPerCallUsd: number;

  public constructor(options: GoogleVtoProviderOptions) {
    this.httpClient = options.httpClient;
    this.costPerCallUsd = options.costPerCallUsd ?? 0;
  }

  public async tryOn(req: TryOnRequest, ctx: ProviderContext): Promise<TryOnResult> {
    const garmentRef = req.params?.garmentImage;
    const instance: Record<string, unknown> = {
      personImage: { image: { gcsUri: imageRefToInput(req.personImage) } },
      productImages: [
        {
          image: garmentRef
            ? { gcsUri: imageRefToInput(garmentRef) }
            : { productId: req.productId },
        },
      ],
    };
    const parameters: Record<string, unknown> = {
      sampleCount: req.params?.numSamples ?? 1,
    };
    if (req.params?.seed !== undefined) {
      parameters['seed'] = req.params.seed;
    }
    ctx.logger.debug('googleVto.tryOn', { tenantId: req.tenantId });
    const response = await this.httpClient.predict(
      { instances: [instance], parameters },
      ctx.signal,
    );
    const url = response.predictions?.[0]?.resultImageUrl;
    if (typeof url !== 'string' || url.length === 0) {
      // fail-closed: no prediction / no surfaced url is a failure, not an empty success.
      throw new Error('google-vto: response contained no result image url');
    }
    return validateProviderResult(
      {
        resultImageUrl: url,
        provider: this.id,
        latencyMs: 0,
        cached: false,
        costUsd: this.costPerCallUsd,
      },
      'google-vto',
    );
  }
}
